name: imaxb2bflutter
description: "outsource project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  get: ^4.6.6
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0



dev_dependencies:
  flutter_driver:
    sdk: flutter
  test:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Italic.ttf
          style: italic
        - asset: assets/fonts/Prompt-Bold.ttf
          weight: 700
